[[main]]
name = "O nas"
url = "pl/about/"
weight = 1

[[main]]
name = "Członkowie"
url = "pl/members/"
weight = 2

[[main]]
name = "O'Death"
url = "pl/plays/o-death/"
weight = 3

[[main]]
name = "Wydarzenia"
url = "pl/events/"
weight = 4
